export enum Status {
  None = 'None',
  Active = 'ACTIVE',
  Draft = 'DRAFT',
  CaseInitiated = 'CASE INITIATED',
  CaseSubmitted = 'CASE SUBMITTED',
  ScrutinyProcessed = 'SCRUTINY PROCESSED',
  ScrutinyInprocess = 'SCRUTINY INPROCESS',
  ScrutinyAllocated = 'SCRUTINY ALLOCATED',
  ScrutinyPending = 'SCRUTINY PENDING',
  ScrutinyHold = 'SCRUTINY HOLD',
  DataEntryAllocated = 'DATA ENTRY ALLOCATED',
  DataEntryInprocess = 'DATA ENTRY INPROCESS',
  DataEntryProcessed = 'DATA ENTRY PROCESSED',
  DataEntryPending = 'DATA ENTRY PENDING',
  DataEntryHold = 'DATA ENTRY HOLD',
  CheckerAllocated = 'CHECKER ALLOCATED',
  CheckerInprocessed = 'CHECKER INPROCESS',
  CheckerProcessed = 'CHECKER PROCESSED',
  CheckerPending = 'CHECKER PENDING',
  CheckerHold = 'CHECKER HOLD',
  PhysicalVerification = 'PHYSICAL VERIFCATION PROCESSED',
  
}
